# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python ./catsFandom/manage.py runserver  0.0.0.0:8000
    volumes:
      - .:/usr/src/catsFandom
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=catsFandom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    container_name: pgdb
#    volumes:
#      - ./pgdbdata:/var/lib/postgresql/data/
#    command:
#      - sh -c "docker cp /pgdbdata/backup.sql pgdb:/var/lib/postgresql/data/"
#      - pg_restore -U postgres -h pgdb -d catsFandom /var/lib/postgresql/data/backup.sql

#
#volumes:
#  pgdbdata: null
