# Generated by Django 5.0.4 on 2024-05-01 08:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
