# Generated by Django 5.0.4 on 2024-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_alter_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
