# Generated by Django 5.0.4 on 2024-05-01 16:13

import cat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_cat_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-is_published', 'title']},
        ),
        migrations.AddField(
            model_name='cat',
            name='born_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cat.models.get_upload_path, verbose_name='photo'),
        ),
    ]
