# Generated by Django 5.0.4 on 2024-05-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_alter_cat_options_cat_born_year_alter_cat_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
